### ISSUE TITLE
[wish] Make Usable with http_archive() / git_repository()?

### ISSUE THREAD

**Issue by AE1020** [erenon/bazel_clang_tidy#1]
I don't know much about Bazel, but even so...I tried adding this to a project and it seemed to work very well on a first try.  Very nice!

However, it seems to me that making a copy of the source in the `/clang_tidy` folder (as suggested in the README.md) is not ideal.  It means it doesn't focus improvements/bugfixes/documentation to a central location.

Could this be rethought so that instead of being framed as a demo project, the root directory had a BUILD.bazel that offered the functionality as a package so it could be linked to?  As an example, how the Google Test is done?

https://github.com/google/googletest

Since as I said I don't know Bazel beyond what I have read today, that is the only example I have to point at.  Would the same model work here, or is does something about being invoked with "--aspects" make it harder?

**Comment by erenon** [comment]
Hi, thanks for noting this. Unfortunately, I will not have time to make this change in the near future - a PR would be welcome (the only thing that really needs to be decided, is the name of the repository, e.g: bazel_clang_tidy, so the recommended aspect invocation becomes `--aspects @bazel_clang_tidy//clang_tidy.bzl%clang_tidy_aspect`)

On the other hand, this is a single file. You have to either update your WORKSPACE file, or the copied file itself - the update will not be automatic. And if you depend on an external project like this, you risk a build break if this repo goes away by accident - so this is a double edged sword.

**Comment by slsyy** [comment]
I have installed the implementation from @silvergasp and it works pretty good. Can we close the issue?
