### ISSUE TITLE
How to run this with a different clang-tidy

### ISSUE THREAD

**Issue by ghorn** [erenon/bazel_clang_tidy#14]
Using [this repo](https://github.com/grailbio/bazel-toolchain), I have access to a bazel-controlled `clang-tidy` binary `@llvm_toolchain//llvm:bin/clang-tidy`. How hard would it be to support using that clang-tidy instead of a system clang-tidy?

**Comment by erenon** [comment]
You need to make this target: https://github.com/erenon/bazel_clang_tidy/blob/master/clang_tidy/BUILD#L4
depend on @llvm_toolchain//llvm:bin/clang-tidy, and change this file: https://github.com/erenon/bazel_clang_tidy/blob/master/clang_tidy/run_clang_tidy.sh to invoke that clang-tidy binary.

**Comment by ghorn** [comment]
Thank you, that worked for me. I had to hardcode the path as `external/llvm_toolchain/llvm/bin/clang-tidy` because I couldn't figure out how to use `$(location` in the rule - I don't understand bazel rules very well. This is good enough for the moment though.
