### ISSUE TITLE
Conflict with rules proto: "cannot load '@rules_cc//cc:action_names.bzl': no such file"

### ISSUE THREAD

**Issue by gioannidis** [erenon/bazel_clang_tidy#8]
### Overview

`bazel_clang_tidy` seems to conflict with protobuf rules from [`rules_proto`](https://github.com/bazelbuild/rules_proto).
The error I am getting is:
```
clang_tidy/clang_tidy.bzl: cannot load '@rules_cc//cc:action_names.bzl': no such file
```
Details below.

### Steps to reproduce

1. Clone the `bazel_clang_tidy` repository (as of [this commit](https://github.com/erenon/bazel_clang_tidy/commit/1c3a983c054a41be73ac128e3d842a940850b5fe)).
1. Apply the [0001-Added-protobuf-external-dependency-and-sample-proto.patch.gz](https://github.com/erenon/bazel_clang_tidy/files/7027470/0001-Added-protobuf-external-dependency-and-sample-proto.patch.gz) patch.
    * This inserts the rules dependencies from the [`rules_proto`](https://github.com/bazelbuild/rules_proto) repository, updated to the latest commit.
    * It also adds a sample `test.proto` file.
1. Build without invoking `clang-tidy`: works normally

       $ bazel build //example:app

1. Build with `clang-tidy` aspect: raises error (see below)

       bazel build //example:app \
           --aspects clang_tidy/clang_tidy.bzl%clang_tidy_aspect \
           --output_groups=report

### Detailed error message

Invoking the `clang-tidy` aspect with protobuf rules generates the following errors:

```
ERROR: in /path/to/bazel_clang_tidy/clang_tidy/clang_tidy.bzl: cannot load '@rules_cc//cc:action_names.bzl': no such file
ERROR: Analysis of aspect '//clang_tidy:clang_tidy.bzl%clang_tidy_aspect of //example:app' failed; build aborted: in /path/to/bazel_clang_tidy/clang_tidy/clang_tidy.bzl: cannot load '@rules_cc//cc:action_names.bzl': no such file
INFO: Elapsed time: 0.090s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```

### Offending line

Removing the following rule from `WORKSPACE` fixes the `clang-tidy` error, but breaks of course the compilation of `//example:test.proto`:
```
rules_proto_dependencies()
```

**Comment by gioannidis** [comment]
Investigating this further, the root cause is at the `rules_proto` repository end, which fetches an older commit from `rules_cc`.

The [`rules_proto_dependencies()`](https://github.com/bazelbuild/rules_proto/blob/master/proto/repositories.bzl) loads the `rules_cc` [dependencies](https://github.com/bazelbuild/rules_proto/blob/master/proto/private/dependencies.bzl#L98) at commit [`b7fe969`](https://github.com/bazelbuild/rules_cc/commit/b7fe9697c0c76ab2fd431a891dbb9a6a32ed7c3e) (2019-07-22). However, the `action_names.bzl` ([history](https://github.com/bazelbuild/rules_cc/commits/main/cc/action_names.bzl)) was created at a later point: [`4a1c578`](https://github.com/bazelbuild/rules_cc/commit/4a1c578fb0e2fbc06089a3f917e3c3c840c214b4#diff-1f1a733f1ba5ef7e19c965ad2204e1d00848b88d00f8aac4911c9c604ede9073) (2019-08-21).

One workaround is to add the following to the `WORKSPACE` file, after `rules_proto_toolchains()`, which resolves the issue by fetching the latest commit.

```
http_archive(
    name = "rules_cc",
    sha256 = "3cde212ccda3ba152897e7fd354c42eba275878b6d98fe4f2125c684a73f3842",
    strip_prefix = "rules_cc-d66a13e2a01630afcafc4ba411d83e291ecf02bd",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/d66a13e2a01630afcafc4ba411d83e291ecf02bd.tar.gz",
        "https://github.com/bazelbuild/rules_cc/archive/d66a13e2a01630afcafc4ba411d83e291ecf02bd.tar.gz",
    ],
)
```

I am not very experienced with the bazel rules, though. Is there a cleaner way to apply a patch to the `rules_cc` dependency?

**Comment by JulianNeeleman** [comment]
I ran into the same issue. Thanks @gioannidis for figuring out the root cause. For me, the build only succeeded after including your `WORKSPACE` snippet and the `git_repository` declaration for `bazel_clang_tidy` **before** declaring protobuf/gRPC dependencies.

**Comment by erenon** [comment]
Thanks for reporting this. As a tactical measure, we can drop the dependency on "CPP_COMPILE_ACTION_NAME", and hardcode its current value.
